apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tareas
  namespace: tareas-namespace

spec:
  selector:
    matchLabels:
      app: api-tareas
  replicas: 1
  template:
    metadata:
      labels:
        app: api-tareas
    spec:
      
      containers:
        - name: api-tareas
          image: loliconario69/laravel:v2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configuracion-de-tarea
          volumeMounts:
            - mountPath: /app
              name: proyecto
      volumes:
        - name: proyecto
          hostPath: 
            path: "C:\\Users\\Mauro Liguori\\Desktop\\Prog\\ParcialdeProgyPosix\\Tareas"
            type: Directory

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-tareas
  namespace: tareas-namespace
spec:
  selector:
    matchLabels:
      app: mysql-tareas
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-tareas
    spec:
      containers:
        - name: mysql-tareas
          image: mysql:8
          ports:
            - containerPort: 3306
              name: web
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: tareas